INSERT INTO cfg_account_account_state (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_account_account_state (id, name) VALUES (1, '有效');
INSERT INTO cfg_account_account_state (id, name) VALUES (2, '作废');
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (1, '1001', '库存现金', 1);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (3, '1002', '银行存款', 1);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (4, '1121', '应收票据', 1);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (5, '1122', '应收帐款	', 1);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (6, '1123', '预付帐款', 1);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (7, '1132', '应收利息', 1);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (8, '1231', '其它应收款', 1);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (9, '1241', '坏帐准备', 1);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (10, '1601', '固定资产', 1);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (11, '2001', '短期借款', 2);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (12, '2202', '应付帐款', 2);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (13, '2205', '预收帐款', 2);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (14, '2211', '应付职工薪酬', 2);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (15, '2221', '应交税费', 2);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (16, '2232', '应付利息', 2);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (17, '2241', '其他应付款', 2);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (18, '2231', '应付股利', 2);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (19, '4001', '实收资本', 3);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (20, '4002', '资本公积', 3);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (21, '4101', '盈余公积', 3);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (22, '4103', '本年利润', 3);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (23, '4104', '利润分配', 3);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (24, '6001', '主营业务收入', 4);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (25, '6011', '利息收入', 4);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (26, '6021', '手续费收入', 4);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (27, '6301', '营业外收入', 4);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (28, '6401', '主营业务成本', 5);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (29, '6405', '营业税金及附加', 5);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (30, '6411', '利息支出', 5);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (31, '6421', '手续费支出', 5);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (32, '6601', '销售费用', 5);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (33, '6602', '管理费用', 5);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (34, '6603', '财务费用', 5);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (35, '6711', '营业外支出', 5);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (36, '6801', '所得税', 5);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (37, '1003', '短期贷款', 1);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (38, '1004', '长期贷款', 1);
INSERT INTO cfg_account_balance (id, code, name, type) VALUES (39, '2002', '长期借款', 2);
INSERT INTO cfg_account_bank (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_account_bank (id, name) VALUES (1, '中国银行');
INSERT INTO cfg_account_bank (id, name) VALUES (2, '建设银行');
INSERT INTO cfg_account_bank (id, name) VALUES (3, '工商银行');
INSERT INTO cfg_account_company (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_account_company (id, name) VALUES (1, '帮你贷');
INSERT INTO cfg_account_company (id, name) VALUES (2, '大数科技');
INSERT INTO cfg_accounting_period_period_state (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_accounting_period_period_state (id, name) VALUES (1, '生效中');
INSERT INTO cfg_accounting_period_period_state (id, name) VALUES (2, '已关账');
INSERT INTO cfg_accounting_period_period_state (id, name) VALUES (3, '已结转');
INSERT INTO cfg_accounting_rule_fee_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_accounting_rule_fee_type (id, name) VALUES (1, '利息收入');
INSERT INTO cfg_accounting_rule_fee_type (id, name) VALUES (2, '利息支出');
INSERT INTO cfg_accounting_rule_fee_type (id, name) VALUES (3, '员工工资');
INSERT INTO cfg_accounting_rule_fee_type (id, name) VALUES (4, '房屋租金');
INSERT INTO cfg_agent_business_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_agent_business_type (id, name) VALUES (1, '贷款业务');
INSERT INTO cfg_agent_business_type (id, name) VALUES (2, '居间业务');
INSERT INTO cfg_agent_business_type (id, name) VALUES (3, '垫资过桥');
INSERT INTO cfg_agent_channel_type (id, name, type) VALUES (-1,'--请选择--', 0);
INSERT INTO cfg_agent_channel_type (id, name, type) VALUES (1, '内部销售', 1);
INSERT INTO cfg_agent_channel_type (id, name, type) VALUES (2, '外部销售', 2);
INSERT INTO cfg_agent_channel_type (id, name, type) VALUES (3, '外部机构', 2);
INSERT INTO cfg_agent_channel_type (id, name, type) VALUES (4, '内部兼职销售', 1);
INSERT INTO cfg_attendance_ask_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_attendance_ask_type (id, name) VALUES (1, '年假');
INSERT INTO cfg_attendance_ask_type (id, name) VALUES (2, '病假');
INSERT INTO cfg_attendance_ask_type (id, name) VALUES (3, '事假');
INSERT INTO cfg_attendance_ask_type (id, name) VALUES (4, '产假');
INSERT INTO cfg_bridge_cust_certi_type (id, name) VALUES (-1, '--请选择--');
INSERT INTO cfg_bridge_cust_certi_type (id, name) VALUES (2, '身份证');
INSERT INTO cfg_bridge_cust_certi_type (id, name) VALUES (3, '回乡证（仅港澳）');
INSERT INTO cfg_bridge_cust_certi_type (id, name) VALUES (4, '营业执照');
INSERT INTO cfg_bridge_cust_relation_type (id, name) VALUES (-1, '--请选择--');
INSERT INTO cfg_bridge_cust_relation_type (id, name) VALUES (2, '卖方');
INSERT INTO cfg_bridge_cust_relation_type (id, name) VALUES (3, '新贷款共借人');
INSERT INTO cfg_bridge_cust_relation_type (id, name) VALUES (4, '共借人');
INSERT INTO cfg_bridge_cust_relation_type (id, name) VALUES (5, '担保方');
INSERT INTO cfg_bridge_cust_relation_type (id, name) VALUES (6, '承保方');
INSERT INTO cfg_bridge_cust_relation_type (id, name) VALUES (7, '买方');
INSERT INTO cfg_bridge_cust_relation_type (id, name) VALUES (8, '产权人');
INSERT INTO cfg_bridge_estate_type (id, name) VALUES (-1, '--请选择--');
INSERT INTO cfg_bridge_estate_type (id, name) VALUES (2, '住宅');
INSERT INTO cfg_bridge_estate_type (id, name) VALUES (3, '公寓');
INSERT INTO cfg_bridge_estate_type (id, name) VALUES (4, '别墅');
INSERT INTO cfg_bridge_estate_type (id, name) VALUES (5, '商业');
INSERT INTO cfg_bridge_estate_type (id, name) VALUES (6, '办公');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (-1, '--请选择--');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (1, '农村商业银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (2, '中国建设银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (3, '中国银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (4, '中国农业银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (5, '中国工商银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (6, '民生银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (7, '兴业银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (8, '广发银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (9, '上海浦东发展银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (10, '招商银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (11, '交通银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (12, '平安银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (13, '光大银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (14, '华夏银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (15, '中信银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (16, '永亨银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (17, '东亚银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (18, '南洋商业银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (19, '渣打银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (20, '盘谷银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (21, '汇丰银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (22, '星展银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (23, '荷兰银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (24, '恒生银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (25, '花旗银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (26, '中信嘉华银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (27, '北京银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (28, '东莞银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (29, '邮政储蓄银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (30, '包商银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (31, '无');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (32, '上海银行 ');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (33, '华兴银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (34, '华商银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (35, '华润银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (36, '南京银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (37, '南粤银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (38, '友利银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (39, '大众银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (40, '大新银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (41, '宁波银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (42, '宝安融兴村镇银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (43, '工银亚洲银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (44, '广州银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (45, '杭州银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (46, '桂银村镇银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (47, '浙商银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (48, '浙江明泰商业银行');
INSERT INTO cfg_bridge_order_acception_bank_code (id, name) VALUES (49, '深圳发展银行');
INSERT INTO cfg_bridge_order_busi_type (id, name) VALUES (-1, '--请选择--');
INSERT INTO cfg_bridge_order_busi_type (id, name) VALUES (2, '交易');
INSERT INTO cfg_bridge_order_busi_type (id, name) VALUES (3, '非交易');
INSERT INTO cfg_bridge_order_certi_type (id, name) VALUES (-1, '--请选择--');
INSERT INTO cfg_bridge_order_certi_type (id, name) VALUES (2, '身份证');
INSERT INTO cfg_bridge_order_certi_type (id, name) VALUES (3, '回乡证(仅港澳)');
INSERT INTO cfg_bridge_order_certi_type (id, name) VALUES (4, '营业执照');
INSERT INTO cfg_bridge_order_city (id, name) VALUES (-1, '--请选择--');
INSERT INTO cfg_bridge_order_city (id, name) VALUES (2, '北京市');
INSERT INTO cfg_bridge_order_marriage (id, name) VALUES (-1, '--请选择--');
INSERT INTO cfg_bridge_order_marriage (id, name) VALUES (2, '已婚');
INSERT INTO cfg_bridge_order_marriage (id, name) VALUES (3, '未婚');
INSERT INTO cfg_bridge_order_marriage (id, name) VALUES (4, '离异');
INSERT INTO cfg_bridge_order_marriage (id, name) VALUES (5, '丧偶');
INSERT INTO cfg_bridge_order_pay_type (id, name) VALUES (-1, '--请选择--');
INSERT INTO cfg_bridge_order_pay_type (id, name) VALUES (2, '标准业务');
INSERT INTO cfg_bridge_order_pay_type (id, name) VALUES (3, '非标准业务');
INSERT INTO cfg_bridge_order_product_id (id, name) VALUES (-1, '--请选择--');
INSERT INTO cfg_bridge_order_product_id (id, name) VALUES (2, '赎楼贷（交易）');
INSERT INTO cfg_bridge_order_product_id (id, name) VALUES (3, '赎楼贷（非交易）');
INSERT INTO cfg_bridge_order_product_id (id, name) VALUES (4, '提放贷（交易）-赎楼即放款');
INSERT INTO cfg_bridge_order_product_id (id, name) VALUES (5, '提放贷（交易）-过户即放款');
INSERT INTO cfg_bridge_order_product_id (id, name) VALUES (6, '提放贷（非交易）-赎楼即放款');
INSERT INTO cfg_bridge_order_product_id (id, name) VALUES (7, '提放贷（非交易）-抵押即放款');
INSERT INTO cfg_bridge_order_product_id (id, name) VALUES (8, '代购');
INSERT INTO cfg_bridge_order_product_id (id, name) VALUES (9, '二押贷（赎）');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (-1, '--请选择--');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (1, '农村商业银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (2, '中国建设银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (3, '中国银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (4, '中国农业银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (5, '中国工商银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (6, '民生银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (7, '兴业银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (8, '广发银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (9, '上海浦东发展银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (10, '招商银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (11, '交通银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (12, '平安银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (13, '光大银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (14, '华夏银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (15, '中信银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (16, '永亨银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (17, '东亚银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (18, '南洋商业银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (19, '渣打银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (20, '盘谷银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (21, '汇丰银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (22, '星展银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (23, '荷兰银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (24, '恒生银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (25, '花旗银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (26, '中信嘉华银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (27, '北京银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (28, '东莞银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (29, '邮政储蓄银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (30, '包商银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (31, '无');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (32, '上海银行 ');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (33, '华兴银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (34, '华商银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (35, '华润银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (36, '南京银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (37, '南粤银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (38, '友利银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (39, '大众银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (40, '大新银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (41, '宁波银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (42, '宝安融兴村镇银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (43, '工银亚洲银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (44, '广州银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (45, '杭州银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (46, '桂银村镇银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (47, '浙商银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (48, '浙江明泰商业银行');
INSERT INTO cfg_bridge_order_public_fund_bank (id, name) VALUES (49, '深圳发展银行');
INSERT INTO cfg_bridge_order_sex (id, name) VALUES (-1, '--请选择--');
INSERT INTO cfg_bridge_order_sex (id, name) VALUES (2, '男');
INSERT INTO cfg_bridge_order_sex (id, name) VALUES (3, '女');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (-1, '--请选择--');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (1, '农村商业银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (2, '中国建设银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (3, '中国银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (4, '中国农业银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (5, '中国工商银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (6, '民生银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (7, '兴业银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (8, '广发银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (9, '上海浦东发展银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (10, '招商银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (11, '交通银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (12, '平安银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (13, '光大银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (14, '华夏银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (15, '中信银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (16, '永亨银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (17, '东亚银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (18, '南洋商业银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (19, '渣打银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (20, '盘谷银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (21, '汇丰银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (22, '星展银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (23, '荷兰银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (24, '恒生银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (25, '花旗银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (26, '中信嘉华银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (27, '北京银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (28, '东莞银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (29, '邮政储蓄银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (30, '包商银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (31, '无');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (32, '上海银行 ');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (33, '华兴银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (34, '华商银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (35, '华润银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (36, '南京银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (37, '南粤银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (38, '友利银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (39, '大众银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (40, '大新银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (41, '宁波银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (42, '宝安融兴村镇银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (43, '工银亚洲银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (44, '广州银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (45, '杭州银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (46, '桂银村镇银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (47, '浙商银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (48, '浙江明泰商业银行');
INSERT INTO cfg_bridge_order_watch_bank (id, name) VALUES (49, '深圳发展银行');
INSERT INTO cfg_bridge_property_state (id, name) VALUES (-1, '--请选择--');
INSERT INTO cfg_bridge_property_state (id, name) VALUES (2, '正常');
INSERT INTO cfg_bridge_property_state (id, name) VALUES (3, '抵押');
INSERT INTO cfg_bridge_property_state (id, name) VALUES (4, '查封');
INSERT INTO cfg_bridge_property_type (id, name) VALUES (-1, '--请选择--');
INSERT INTO cfg_bridge_property_type (id, name) VALUES (2, '无赎楼无抵押');
INSERT INTO cfg_bridge_property_type (id, name) VALUES (3, '只赎楼');
INSERT INTO cfg_bridge_property_type (id, name) VALUES (4, '只抵押');
INSERT INTO cfg_bridge_property_type (id, name) VALUES (5, '赎楼且抵押');
INSERT INTO cfg_calc_formula_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_calc_formula_type (id, name) VALUES (1, '非交易垫资利息');
INSERT INTO cfg_calc_formula_type (id, name) VALUES (2, '非交易垫资下户费');
INSERT INTO cfg_calc_formula_type (id, name) VALUES (3, '非交易垫资律师费');
INSERT INTO cfg_calc_formula_type (id, name) VALUES (4, '非交易垫资专员工资');
INSERT INTO cfg_calc_formula_type (id, name) VALUES (5, '非交易垫资专员提成');
INSERT INTO cfg_calc_formula_type (id, name) VALUES (6, '非交易垫资经理工资');
INSERT INTO cfg_calc_formula_type (id, name) VALUES (7, '非交易垫资经理提成');
INSERT INTO cfg_calc_formula_type (id, name) VALUES (8, '非交易垫资专员最低提成');
INSERT INTO cfg_calc_formula_type (id, name) VALUES (9, '非交易垫资专员最高提成');
INSERT INTO cfg_calc_formula_type (id, name) VALUES (10, '非交易垫资外勤逐单提成');
INSERT INTO cfg_calc_formula_type (id, name) VALUES (11, '非交易垫资经理最高提成');
INSERT INTO cfg_calc_formula_type (id, name) VALUES (12, '非交易垫资经理最低提成');
INSERT INTO cfg_cbs_business_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_cbs_business_type (id, name) VALUES (1, '居间业务');
INSERT INTO cfg_cbs_business_type (id, name) VALUES (2, '垫资-非交易类');
INSERT INTO cfg_cbs_business_type (id, name) VALUES (3, '抵押业务');
INSERT INTO cfg_cbs_business_type (id, name) VALUES (4, '融资业务');
INSERT INTO cfg_cbs_business_type (id, name) VALUES (6, '垫资-交易类');
INSERT INTO cfg_cbs_business_type (id, name) VALUES (7, '垫资-提放业务');
INSERT INTO cfg_cbs_estate_area (id, city, name) VALUES (0, '2', '全部');
INSERT INTO cfg_cbs_estate_area (id, city, name) VALUES (1, '2', '东西朝海');
INSERT INTO cfg_cbs_estate_area (id, city, name) VALUES (2, '2', '城六区');
INSERT INTO cfg_cbs_estate_area (id, city, name) VALUES (3, '2', '近郊');
INSERT INTO cfg_cbs_estate_area (id, city, name) VALUES (4, '2', '远郊');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (1, '住宅');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (2, '别墅');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (3, '经济适用房');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (4, '商住两用');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (5, '纯商业');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (6, '纯商业实际为居住');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (7, '公司名下房产');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (8, '公寓');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (9, '酒店式公寓');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (10, '央产房');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (11, '公寓式酒店');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (12, '学区房');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (13, '别墅立项为住宅');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (14, '别墅立项为别墅');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (15, '底商');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (16, '标准价');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (17, '公寓住人');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (18, '公寓办公');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (19, '成本价房');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (20, '写字楼');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (21, '商铺');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (22, '商品房');
INSERT INTO cfg_cbs_estate_type (id, name) VALUES (23, '独栋别墅');
INSERT INTO cfg_cbs_identity_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_cbs_identity_type (id, name) VALUES (1, '贷款人');
INSERT INTO cfg_cbs_identity_type (id, name) VALUES (2, '抵押人');
INSERT INTO cfg_cbs_identity_type (id, name) VALUES (3, '连带借款人');
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (-1,'--请选择--', 0);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (101, '订单暂存', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (102, '订单初录入', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (103, '初审不通过', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (104, '初审通过', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (105, '初审上报', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (106, '订单关闭', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (107, '订单已录入', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (108, '复审通过', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (109, '复审不通过', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (110, '订单复暂存', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (111, '已收下户费', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (112, '下户通过', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (113, '下户不通过', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (114, '汇审通过', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (115, '汇审不通过', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (116, '已签约', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (117, '已收费', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (118, '已上报机构', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (119, '同意放款', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (120, '不同意放款', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (121, '放款完成', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (122, '扣款完成', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (123, '解押材料已领取', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (124, '下家已抵押', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (125, '已回款', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (126, '已交接', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (127, '已完结', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (128, '机构已通过', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (129, '确认下家已放款', 1);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (131, '已报单', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (132, '已完成初审准备', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (133, '已初审通过', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (134, '初审不通过', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (135, '初审特殊通过', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (136, '订单关闭', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (137, '已收下户费', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (138, '缓收下户费', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (139, '已安排下户', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (140, '已下户完成', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (141, '已终审通过', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (142, '终审不通过', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (143, '终审特殊通过', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (144, '资金已调度', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (145, '已收费', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (146, '已上报机构', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (147, '资金不平衡', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (148, '资金已平衡', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (149, '同意放款', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (150, '已放款', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (151, '上家已扣款', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (152, '材料已经领取', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (153, '下家已抵押', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (154, '机构已放款', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (155, '已回款', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (156, '已交接', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (157, '已完结', 3);
INSERT INTO cfg_cbs_order_state (id, name, busi_type) VALUES (158, '机构已反馈', 3);
INSERT INTO cfg_cbs_pay_interest_way (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_cbs_pay_interest_way (id, name) VALUES (1, '一次性付息');
INSERT INTO cfg_cbs_pay_interest_way (id, name) VALUES (2, '按周期付息');
INSERT INTO cfg_cbs_pay_way (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_cbs_pay_way (id, name) VALUES (1, '等额本息');
INSERT INTO cfg_cbs_pay_way (id, name) VALUES (2, '等额本金');
INSERT INTO cfg_cbs_pay_way (id, name) VALUES (3, '月息年本');
INSERT INTO cfg_cbs_pay_way (id, name) VALUES (5, '一次性支付');
INSERT INTO cfg_cbs_period_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_cbs_period_type (id, name) VALUES (1, '日');
INSERT INTO cfg_cbs_period_type (id, name) VALUES (2, '三天');
INSERT INTO cfg_cbs_period_type (id, name) VALUES (3, '七天');
INSERT INTO cfg_cbs_period_type (id, name) VALUES (4, '十天');
INSERT INTO cfg_cbs_prod_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_cbs_prod_type (id, name) VALUES (1, '经营贷');
INSERT INTO cfg_cbs_prod_type (id, name) VALUES (2, '消费贷');
INSERT INTO cfg_cbs_prod_type (id, name) VALUES (3, '保单贷');
INSERT INTO cfg_cbs_prod_type (id, name) VALUES (4, '月供贷');
INSERT INTO cfg_cbs_prod_type (id, name) VALUES (5, '公积金贷');
INSERT INTO cfg_cbs_prod_type (id, name) VALUES (6, '信用贷');
INSERT INTO cfg_cbs_rend_object (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_cbs_rend_object (id, name) VALUES (2, '学校');
INSERT INTO cfg_cbs_rend_object (id, name) VALUES (3, '幼儿园');
INSERT INTO cfg_cbs_rend_object (id, name) VALUES (4, '医院');
INSERT INTO cfg_certificate_certi_state (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_certificate_certi_state (id, name) VALUES (1, '收押中');
INSERT INTO cfg_certificate_certi_state (id, name) VALUES (2, '出借中');
INSERT INTO cfg_certificate_certi_state (id, name) VALUES (3, '已归还');
INSERT INTO cfg_certificate_certi_state (id, name) VALUES (4, '免归还');
INSERT INTO cfg_certificate_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_certificate_type (id, name) VALUES (1, '身份证');
INSERT INTO cfg_certificate_type (id, name) VALUES (2, '房产证');
INSERT INTO cfg_commission_base_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_commission_base_type (id, name) VALUES (1, '业务额');
INSERT INTO cfg_commission_base_type (id, name) VALUES (2, '手续费');
INSERT INTO cfg_commission_business_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_commission_business_type (id, name) VALUES (1, '贷款业务');
INSERT INTO cfg_commission_business_type (id, name) VALUES (2, '居间业务');
INSERT INTO cfg_commission_business_type (id, name) VALUES (3, '垫资过桥');
INSERT INTO cfg_commission_channel_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_commission_channel_type (id, name) VALUES (1, '外部员工');
INSERT INTO cfg_commission_channel_type (id, name) VALUES (2, '内部员工');
INSERT INTO cfg_commission_level (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_commission_level (id, name) VALUES (1, '基础员工');
INSERT INTO cfg_commission_level (id, name) VALUES (2, '团队负责人');
INSERT INTO cfg_commission_level (id, name) VALUES (3, '部门经理');
INSERT INTO cfg_commission_product_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_commission_product_type (id, name) VALUES (2, '抵押贷款');
INSERT INTO cfg_commission_product_type (id, name) VALUES (3, '居间业务');
INSERT INTO cfg_commission_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_commission_type (id, name) VALUES (1, '销售人员');
INSERT INTO cfg_commission_type (id, name) VALUES (2, '风控人员');
INSERT INTO cfg_commission_type (id, name) VALUES (3, '服务人员');
INSERT INTO cfg_commission_way (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_commission_way (id, name) VALUES (1, '简单比例');
INSERT INTO cfg_commission_way (id, name) VALUES (2, '累进比例');
INSERT INTO cfg_commission_way (id, name) VALUES (3, '累进');
INSERT INTO cfg_cust_city (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_cust_city (id, name) VALUES (1, '北京');
INSERT INTO cfg_cust_city (id, name) VALUES (2, '上海');
INSERT INTO cfg_cust_info_original (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_cust_info_original (id, name) VALUES (1, '陌生拜访');
INSERT INTO cfg_cust_info_original (id, name) VALUES (2, '互联网');
INSERT INTO cfg_cust_info_original (id, name) VALUES (3, '熟人推荐');
INSERT INTO cfg_cust_info_original (id, name) VALUES (4, '电话筛选');
INSERT INTO cfg_cust_is_new_stockholder (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_cust_is_new_stockholder (id, name) VALUES (1, '是');
INSERT INTO cfg_cust_is_new_stockholder (id, name) VALUES (2, '否');
INSERT INTO cfg_cust_job (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_cust_job (id, name) VALUES (1, '做生意');
INSERT INTO cfg_cust_job (id, name) VALUES (2, '上班');
INSERT INTO cfg_cust_sales_state (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_cust_sales_state (id, name) VALUES (1, '准客户');
INSERT INTO cfg_cust_sales_state (id, name) VALUES (2, '服务客户');
INSERT INTO cfg_cust_sales_state (id, name) VALUES (3, '服务完结客户');
INSERT INTO cfg_cust_sex (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_cust_sex (id, name) VALUES (1, '男');
INSERT INTO cfg_cust_sex (id, name) VALUES (2, '女');
INSERT INTO cfg_cust_why_borrow (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_cust_why_borrow (id, name) VALUES (1, '做生意用钱');
INSERT INTO cfg_cust_why_borrow (id, name) VALUES (2, '增贷');
INSERT INTO cfg_cust_why_borrow (id, name) VALUES (3, '延长贷款期限');
INSERT INTO cfg_employee_city (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_employee_city (id, name) VALUES (1, '北京');
INSERT INTO cfg_employee_city (id, name) VALUES (2, '上海');
INSERT INTO cfg_employee_city (id, name) VALUES (3, '武汉');
INSERT INTO cfg_employee_manage_grade (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_employee_manage_grade (id, name) VALUES (1, '普通员工');
INSERT INTO cfg_employee_manage_grade (id, name) VALUES (2, '组长');
INSERT INTO cfg_employee_manage_grade (id, name) VALUES (3, '部门经理');
INSERT INTO cfg_employee_manage_grade (id, name) VALUES (4, '总监');
INSERT INTO cfg_employee_position_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_employee_position_type (id, name) VALUES (1, '全职岗位');
INSERT INTO cfg_employee_position_type (id, name) VALUES (2, '兼职岗位');
INSERT INTO cfg_employee_tech_grade (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_employee_tech_grade (id, name) VALUES (1, '初级');
INSERT INTO cfg_employee_tech_grade (id, name) VALUES (2, '中级');
INSERT INTO cfg_employee_tech_grade (id, name) VALUES (3, '高级');
INSERT INTO cfg_format_info_client_mapping (id, client_key, format_info_key, ocr_file_type) VALUES (1, 'address', '发证地址', 1);
INSERT INTO cfg_format_info_client_mapping (id, client_key, format_info_key, ocr_file_type) VALUES (2, 'nationality', '民族', 1);
INSERT INTO cfg_format_info_client_mapping (id, client_key, format_info_key, ocr_file_type) VALUES (3, 'start_date', '身份证有效期起', 1);
INSERT INTO cfg_format_info_client_mapping (id, client_key, format_info_key, ocr_file_type) VALUES (4, 'end_date', '身份证有效期止', 1);
INSERT INTO cfg_format_info_client_mapping (id, client_key, format_info_key, ocr_file_type) VALUES (5, 'issue', '发证机关', 1);
INSERT INTO cfg_format_info_client_mapping (id, client_key, format_info_key, ocr_file_type) VALUES (6, '房产证号', '房产证号', 6);
INSERT INTO cfg_format_info_client_mapping (id, client_key, format_info_key, ocr_file_type) VALUES (7, '权利人', '产权人', 6);
INSERT INTO cfg_format_info_client_mapping (id, client_key, format_info_key, ocr_file_type) VALUES (8, '共有情况', '共有情况', 6);
INSERT INTO cfg_format_info_client_mapping (id, client_key, format_info_key, ocr_file_type) VALUES (9, '坐落', '房屋坐落', 6);
INSERT INTO cfg_format_info_client_mapping (id, client_key, format_info_key, ocr_file_type) VALUES (10, '不动产单元号', '不动产单元号', 6);
INSERT INTO cfg_format_info_client_mapping (id, client_key, format_info_key, ocr_file_type) VALUES (11, '土地权利类型', '土地权利类型', 6);
INSERT INTO cfg_format_info_client_mapping (id, client_key, format_info_key, ocr_file_type) VALUES (12, '房屋权利类型', '房屋权利类型', 6);
INSERT INTO cfg_format_info_client_mapping (id, client_key, format_info_key, ocr_file_type) VALUES (13, '土地权利性质/取得方式', '土地权利性质/取得方式', 6);
INSERT INTO cfg_format_info_client_mapping (id, client_key, format_info_key, ocr_file_type) VALUES (14, '房屋权利性质/取得方式', '房屋权利性质/取得方式', 6);
INSERT INTO cfg_format_info_client_mapping (id, client_key, format_info_key, ocr_file_type) VALUES (15, '土地用途', '土地用途', 6);
INSERT INTO cfg_format_info_client_mapping (id, client_key, format_info_key, ocr_file_type) VALUES (16, '房屋用途', '房屋用途', 6);
INSERT INTO cfg_format_info_client_mapping (id, client_key, format_info_key, ocr_file_type) VALUES (17, '建筑面积', '建筑面积', 6);
INSERT INTO cfg_format_info_client_mapping (id, client_key, format_info_key, ocr_file_type) VALUES (18, '使用期限', '使用期限', 6);
INSERT INTO cfg_format_info_data_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_format_info_data_type (id, name) VALUES (1, 'Integer');
INSERT INTO cfg_format_info_data_type (id, name) VALUES (2, 'Long');
INSERT INTO cfg_format_info_data_type (id, name) VALUES (3, 'String');
INSERT INTO cfg_format_info_data_type (id, name) VALUES (4, 'Date');
INSERT INTO cfg_format_info_data_type (id, name) VALUES (5, 'BigDecimal');
INSERT INTO cfg_format_info_if_scatter (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_format_info_if_scatter (id, name) VALUES (1, '是');
INSERT INTO cfg_format_info_if_scatter (id, name) VALUES (2, '否');
INSERT INTO cfg_format_info_who_object (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_format_info_who_object (id, name) VALUES (1, 'Order');
INSERT INTO cfg_group_grade (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_group_grade (id, name) VALUES (1, '部');
INSERT INTO cfg_group_grade (id, name) VALUES (2, '组');
INSERT INTO cfg_knowledge_question_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_knowledge_question_type (id, name) VALUES (1, '产品类');
INSERT INTO cfg_knowledge_question_type (id, name) VALUES (2, '销售类');
INSERT INTO cfg_knowledge_question_type (id, name) VALUES (3, '服务类');
INSERT INTO cfg_new_load_condition (id, name) VALUES (-1, '--请选择--');
INSERT INTO cfg_new_load_condition (id, name) VALUES (2, '他证');
INSERT INTO cfg_new_load_condition (id, name) VALUES (3, '回执');
INSERT INTO cfg_new_load_condition (id, name) VALUES (4, '其他');
INSERT INTO cfg_new_load_way (id, name) VALUES (-1, '--请选择--');
INSERT INTO cfg_new_load_way (id, name) VALUES (2, '抵押贷');
INSERT INTO cfg_new_load_way (id, name) VALUES (3, '按揭贷');
INSERT INTO cfg_new_load_way (id, name) VALUES (4, '公积金');
INSERT INTO cfg_new_load_way (id, name) VALUES (5, '组合贷');
INSERT INTO cfg_new_load_way (id, name) VALUES (6, '一次性付款');
INSERT INTO cfg_order_doc_type (id, ch_name, en_name, file_desc, need_condition, file_type) VALUES (1, '身份证明', 'certificate', '（编码：A1_01-）①大陆人士：身份证+新身份证办理回执（若身份证有效期6个月以下）。②港澳人士：港澳居民身份证+港澳居民来往内地通行证（回乡证）+身份变更声明书（如有）', null, '个人资料');
INSERT INTO cfg_order_doc_type (id, ch_name, en_name, file_desc, need_condition, file_type) VALUES (2, '婚姻证明', 'marriage', '（编码：A1_02-）①未婚：单身承诺书；②已婚：结婚证；③A离异（有离婚证）：离婚证+离婚协议+单身承诺书；③B离异（无离婚证）：离婚判决书+单身承诺书；④丧偶：配偶死亡证明+单身承诺书', null, '个人资料');
INSERT INTO cfg_order_doc_type (id, ch_name, en_name, file_desc, need_condition, file_type) VALUES (3, '户口本', 'householdRegister', '（编码：A1_03-）整本，首页至尾页', null, '个人资料');
INSERT INTO cfg_order_doc_type (id, ch_name, en_name, file_desc, need_condition, file_type) VALUES (4, '诉讼材料', 'litigationMaterials', '（编码：A1_04-）有诉讼：判决书、执行结案证明等；无诉讼则无须上传。', null, '个人资料');
INSERT INTO cfg_order_doc_type (id, ch_name, en_name, file_desc, need_condition, file_type) VALUES (5, '征信', 'creditReporting', '（编码：A1_05-）整本，首页至尾页', null, '个人资料');
INSERT INTO cfg_order_doc_type (id, ch_name, en_name, file_desc, need_condition, file_type) VALUES (6, '房产证', 'propertyOwnership', '（编码：A2_01-）整本，首页至尾页', null, '房产');
INSERT INTO cfg_order_doc_type (id, ch_name, en_name, file_desc, need_condition, file_type) VALUES (8, '房产评估', 'houseEstimate', '（编码：A2_02-）有：评估报告（评估截图）；无则无须上传。', '', '房产');
INSERT INTO cfg_order_doc_type (id, ch_name, en_name, file_desc, need_condition, file_type) VALUES (9, '原贷款合同', 'originalLoanContract', '编码：A3_01-）有：所有合同的关键信息页(借款时间、金额、借款帐户、抵押物清单、签字页等)无：三选一，①查档+征信体现原贷款；②查档+放款流水+还款流水；③查档+原贷款信息核实表', '', '原贷款资料');
INSERT INTO cfg_order_doc_type (id, ch_name, en_name, file_desc, need_condition, file_type) VALUES (10, '还款清单', 'backLoanList', '（编码：A3_02-）征信未显示最近1期还款记录：最新还款清单或还款凭证；征信已显示最近1期还款记录：则无须上传。', '', '原贷款资料');
INSERT INTO cfg_order_doc_type (id, ch_name, en_name, file_desc, need_condition, file_type) VALUES (11, '提前还款回执', 'beforeBackReceived', '（编码：A3_03-）有：提前还款回执；无则无须上传。', '', '原贷款资料');
INSERT INTO cfg_order_doc_type (id, ch_name, en_name, file_desc, need_condition, file_type) VALUES (12, '赎楼要件', 'houseImportFile', '（编码：A3_04-）银行卡复印件/公司印鉴卡', '', '原贷款资料');
INSERT INTO cfg_order_doc_type (id, ch_name, en_name, file_desc, need_condition, file_type) VALUES (13, '贷款批复', 'loanApproved', '（编码：A4_01-）有：银行系统截图/贷款合同；无：同贷批复核实表', '', '新贷款资料');
INSERT INTO cfg_order_doc_type (id, ch_name, en_name, file_desc, need_condition, file_type) VALUES (14, '回款要件', 'backMoneyImpFiles', '（编码：A4_02-）银行卡复印件', '', '新贷款资料');
INSERT INTO cfg_order_doc_type (id, ch_name, en_name, file_desc, need_condition, file_type) VALUES (15, '第三方资料', 'thiredDocs', '编码：A4_08-）身份证/营业执照', '', '新贷款资料');
INSERT INTO cfg_order_doc_type (id, ch_name, en_name, file_desc, need_condition, file_type) VALUES (16, '查档', 'consultFiles', '（编码：A5_01-）有效期内查档单', '', '放款资料');
INSERT INTO cfg_order_doc_type (id, ch_name, en_name, file_desc, need_condition, file_type) VALUES (17, '公证书', 'notarization', '（编码：A5_02-）有：整本，首页至尾页；无则无须上传。	', '', '放款资料');
INSERT INTO cfg_order_doc_type (id, ch_name, en_name, file_desc, need_condition, file_type) VALUES (18, '法律文本', 'lawFile', '编码：A5_03-）一套原件', '', '放款资料');
INSERT INTO cfg_order_doc_type (id, ch_name, en_name, file_desc, need_condition, file_type) VALUES (19, '面签照', 'faceApprovePic', '编码：A5_04-）清晰人物及签字照/视频（机构面签）', '', '放款资料');
INSERT INTO cfg_order_doc_type (id, ch_name, en_name, file_desc, need_condition, file_type) VALUES (20, '其他', 'others', '（编码：A6_01-）其他补充资料', '', '其他');
INSERT INTO cfg_organ_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_organ_type (id, name) VALUES (1, '银行');
INSERT INTO cfg_organ_type (id, name) VALUES (2, '机构');
INSERT INTO cfg_original_loan_bank (id, name) VALUES (-1, '--请选择--');
INSERT INTO cfg_original_loan_foreclosure_type (id, name) VALUES (-1, '--请选择--');
INSERT INTO cfg_original_loan_foreclosure_type (id, name) VALUES (2, '柜台手动扣款');
INSERT INTO cfg_original_loan_foreclosure_type (id, name) VALUES (3, '系统自动扣款');
INSERT INTO cfg_original_loan_foreclosure_type (id, name) VALUES (4, '客户经理手动操作');
INSERT INTO cfg_original_loan_foreclosure_type (id, name) VALUES (5, 'APP操作扣款');
INSERT INTO cfg_original_loan_foreclosure_type (id, name) VALUES (6, '网银操作扣款');
INSERT INTO cfg_original_loan_foreclosure_type (id, name) VALUES (7, '电话银行预约扣款');
INSERT INTO cfg_original_loan_foreclosure_type (id, name) VALUES (8, '预存系统扣款');
INSERT INTO cfg_original_loan_organ_type (id, name) VALUES (-1, '--请选择--');
INSERT INTO cfg_original_loan_organ_type (id, name) VALUES (2, '银行');
INSERT INTO cfg_original_loan_organ_type (id, name) VALUES (3, '机构');
INSERT INTO cfg_original_loan_organ_type (id, name) VALUES (4, '个人');
INSERT INTO cfg_original_loan_type (id, name) VALUES (-1, '--请选择--');
INSERT INTO cfg_original_loan_type (id, name) VALUES (2, '抵押贷');
INSERT INTO cfg_original_loan_type (id, name) VALUES (3, '按揭贷');
INSERT INTO cfg_original_loan_type (id, name) VALUES (4, '公积金');
INSERT INTO cfg_payment_in_out (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_payment_in_out (id, name) VALUES (1, '收');
INSERT INTO cfg_payment_in_out (id, name) VALUES (2, '支');
INSERT INTO cfg_payment_offset (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_payment_offset (id, name) VALUES (1, '已核销');
INSERT INTO cfg_payment_offset (id, name) VALUES (2, '未核销');
INSERT INTO cfg_payment_pay_data_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_payment_pay_data_type (id, name) VALUES (1, '实');
INSERT INTO cfg_payment_pay_data_type (id, name) VALUES (2, '应');
INSERT INTO cfg_payment_pay_state (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_payment_pay_state (id, name) VALUES (1, '待支付');
INSERT INTO cfg_payment_pay_state (id, name) VALUES (3, '支付中');
INSERT INTO cfg_payment_pay_state (id, name) VALUES (4, '撤销');
INSERT INTO cfg_payment_pay_state (id, name) VALUES (5, '支付成功');
INSERT INTO cfg_payment_pay_state (id, name) VALUES (6, '已确认');
INSERT INTO cfg_payment_pay_state (id, name) VALUES (7, '待确认');
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (-1,'--请选择--', 0, 0, 0);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (1, '应收利息', 1, 1, 18);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (2, '应付利息', 1, 2, 8);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (3, '应收手续费', 1, 1, 14);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (5, '应付工资', 1, 2, 23);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (6, '应付佣金', 1, 2, 24);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (7, '应付渠道费用', 1, 2, 25);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (8, '实付利息', 1, 4, 1);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (9, '应收律师费', 1, 1, 15);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (10, '应收公证费', 1, 1, 16);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (11, '应收执照费', 1, 1, 17);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (12, '实付办公费用', 2, 4, 0);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (13, '实收客户借款', 1, 3, 20);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (14, '实收手续费', 1, 3, 3);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (15, '实收律师费', 1, 3, 9);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (16, '实收公证费', 1, 3, 10);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (17, '实收执照费', 1, 3, 11);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (18, '实收利息', 1, 3, 1);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (19, '实付客户贷款', 1, 4, 21);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (20, '应收客户借款', 1, 1, 13);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (21, '应付客户贷款', 1, 2, 19);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (23, '实付工资', 1, 4, 5);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (24, '实付佣金', 1, 4, 6);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (25, '实付渠道费用', 1, 4, 7);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (26, '应收客户贷款', 1, 1, 28);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (27, '应付客户借款', 1, 2, 29);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (28, '实收客户贷款', 1, 3, 26);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (29, '实付客户借款', 1, 4, 27);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (30, '应收下户费', 1, 1, 31);
INSERT INTO cfg_payment_pay_type (id, name, busi_type, fee_type, relate_id) VALUES (31, '实收下户费', 1, 3, 30);
INSERT INTO cfg_performance_commission_process (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_performance_commission_process (id, name) VALUES (1, '已经核算');
INSERT INTO cfg_performance_commission_process (id, name) VALUES (2, '已经发放');
INSERT INTO cfg_position_is_commission (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_position_is_commission (id, name) VALUES (1, '是');
INSERT INTO cfg_position_is_commission (id, name) VALUES (2, '否');
INSERT INTO cfg_product_bank_id (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_product_bank_id (id, name) VALUES (1, '中国银行');
INSERT INTO cfg_product_bank_id (id, name) VALUES (2, '工商银行');
INSERT INTO cfg_product_bank_id (id, name) VALUES (3, '招商银行');
INSERT INTO cfg_product_bank_id (id, name) VALUES (4, '贯泽信');
INSERT INTO cfg_product_bank_id (id, name) VALUES (5, '小科金融');
INSERT INTO cfg_product_product_state (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_product_product_state (id, name) VALUES (1, '生效中');
INSERT INTO cfg_product_product_state (id, name) VALUES (2, '已停售');
INSERT INTO cfg_product_product_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_product_product_type (id, name) VALUES (1, '抵押贷');
INSERT INTO cfg_product_product_type (id, name) VALUES (2, '经营贷');
INSERT INTO cfg_product_product_type (id, name) VALUES (3, '消费贷');
INSERT INTO cfg_reminder_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_reminder_type (id, name) VALUES (1, '关键节点提醒');
INSERT INTO cfg_reminder_type (id, name) VALUES (2, '业务类通知');
INSERT INTO cfg_reminder_type (id, name) VALUES (3, '订单长时间不动提醒');
INSERT INTO cfg_reminder_way (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_reminder_way (id, name) VALUES (1, '钉钉');
INSERT INTO cfg_reminder_way (id, name) VALUES (2, '短信');
INSERT INTO cfg_reminder_way (id, name) VALUES (3, '微信');
INSERT INTO cfg_resource_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_resource_type (id, name) VALUES (1, '链接');
INSERT INTO cfg_resource_type (id, name) VALUES (2, '按钮');
INSERT INTO cfg_resource_type (id, name) VALUES (3, '数据');
INSERT INTO cfg_role_resource_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_role_resource_type (id, name) VALUES (1, '可读');
INSERT INTO cfg_role_resource_type (id, name) VALUES (2, '读增改');
INSERT INTO cfg_role_resource_type (id, name) VALUES (3, '读增改删');
INSERT INTO cfg_salary_extend_state (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_salary_extend_state (id, name) VALUES (1, '已发放');
INSERT INTO cfg_salary_extend_state (id, name) VALUES (2, '未发放');
INSERT INTO cfg_task_task_period (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_task_task_period (id, name) VALUES (1, '天');
INSERT INTO cfg_task_task_period (id, name) VALUES (2, '周');
INSERT INTO cfg_task_task_period (id, name) VALUES (3, '月');
INSERT INTO cfg_task_task_period (id, name) VALUES (4, '年');
INSERT INTO cfg_task_task_state (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_task_task_state (id, name) VALUES (1, '待完成');
INSERT INTO cfg_task_task_state (id, name) VALUES (2, '进行中');
INSERT INTO cfg_task_task_state (id, name) VALUES (3, '已完成');
INSERT INTO cfg_task_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_task_type (id, name) VALUES (1, '销售任务');
INSERT INTO cfg_task_type (id, name) VALUES (2, '一般日常');
INSERT INTO cfg_tel_sales_result (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_tel_sales_result (id, name) VALUES (1, '不接');
INSERT INTO cfg_tel_sales_result (id, name) VALUES (2, '不需要');
INSERT INTO cfg_tel_sales_result (id, name) VALUES (3, '没空');
INSERT INTO cfg_tel_sales_result (id, name) VALUES (4, '需要进一步了解');
INSERT INTO cfg_tel_sales_task_delay (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_tel_sales_task_delay (id, name) VALUES (1, '一天后');
INSERT INTO cfg_tel_sales_task_delay (id, name) VALUES (2, '两天后');
INSERT INTO cfg_tel_sales_task_delay (id, name) VALUES (3, '三天后');
INSERT INTO cfg_tel_sales_task_delay (id, name) VALUES (4, '一周后');
INSERT INTO cfg_tel_sales_task_delay (id, name) VALUES (5, '一月后');
INSERT INTO cfg_work_flow_work_type (id, name) VALUES (-1,'--请选择--');
INSERT INTO cfg_work_flow_work_type (id, name) VALUES (1, '订单处理工作');
INSERT INTO cfg_work_flow_work_type (id, name) VALUES (2, '其他工作');
